apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: laravel-demo.k8s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: laravel-demo-service
            port:
              number: 80
