apiVersion: v1
kind: Service
metadata:
  name: laravel-demo-service
  labels:
    app: laravel-demo
spec:
  selector:
    app: laravel-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
